[lint]
ignore = [
    "ANN101",
    "ANN102",
    "C901",
    "D100",
    "D101",
    "D102",
    "D103",
    "D211",
    "D213",
    "E501",
    "EM101",
    "ERA001",
    "F403",
    "F405",
    "PLR0912",
    "PLR0915",
    "PLR2004",
    "T201",
    "TRY003",
]
select = ["ALL"]
